version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "uv"
    directory: "/templates/python-grpc"
    schedule:
      interval: "weekly"
  - package-ecosystem: "uv"
    directory: "/templates/python"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/templates/nestjs"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/templates/nextjs"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/templates/golang-grpc"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/templates/golang"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/templates/terraform-google-cloud/envs/dev"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/templates/terraform-google-cloud/envs/prod"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/templates/golang-grpc"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/templates/golang"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/templates/nestjs"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/templates/nextjs"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/templates/python-grpc"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/templates/python"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker-compose"
    directory: "/templates/golang-grpc"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker-compose"
    directory: "/templates/golang"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker-compose"
    directory: "/templates/nestjs"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker-compose"
    directory: "/templates/python-grpc"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker-compose"
    directory: "/templates/python"
    schedule:
      interval: "weekly"
