name: python-grpc-template-ci

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with:
          python-version-file: .python-version

      - uses: astral-sh/setup-uv@v8.3.2
        with:
          enable-cache: true

      - uses: bufbuild/buf-action@v1
        with:
          version: "1.72.0"
          setup_only: true

      - name: Setup
        run: make setup

      - name: Proto lint
        run: make proto-lint

      - name: Proto breaking check
        if: github.event_name == 'pull_request'
        run: buf breaking --against "${{ github.event.repository.clone_url }}#format=git,commit=${{ github.event.pull_request.base.sha }}"

      - name: Lint
        run: make lint

      - name: Format check
        run: uv run ruff format --check .

      - name: Typecheck
        run: make typecheck

      - name: Test
        run: make test
