name: nestjs-template-ci

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: pnpm

      - name: Setup
        run: make setup

      - name: Lint
        run: make lint

      - name: Format
        run: pnpm exec prettier --check .

      - name: Test
        run: make test

      - name: Build
        run: pnpm run build
