name: nextjs-template-ci

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup
        run: make setup

      - name: Lint
        run: make lint

      - name: Format
        run: pnpm exec prettier --check .

      - name: Test
        run: make test

      - name: Build
        run: make build

      - name: Build
        run: pnpm run build
